### ISSUE TITLE
Application Crashes

### ISSUE THREAD

**Issue by hammadbutt** [varunon9/Remote-Control-PC#10]
Application gets terminated whenever I press the Live Screen displaying the following error on the server side. 

java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2601)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at remotecontrolpc.desktop.server.Server.connect(Server.java:51)
	at remotecontrolpc.desktop.MainScreen$4.run(MainScreen.java:244)
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)
	at java.io.ObjectOutputStream.writeNonProxyDesc(ObjectOutputStream.java:1286)
	at java.io.ObjectOutputStream.writeClassDesc(ObjectOutputStream.java:1231)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1427)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeFatalException(ObjectOutputStream.java:1577)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:351)
	at remotecontrolpc.desktop.filesharing.Screenshot$1.run(Screenshot.java:39)

**Comment by varunon9** [comment]
I have updated Android as well as Desktop app. Please download latest code and check once again.

**Comment by hammadbutt** [comment]
Thank you for your response. Let me take a look again.

**Comment by hammadbutt** [comment]
I have tried the updated code, but it doesn't connect with the desktop application. Here is a screenshot, you can see the error at the desktop side. 

![2017-08-08](https://user-images.githubusercontent.com/23361788/29082407-d1b5fef4-7c7e-11e7-9f62-f75c27a7089f.png)

**Comment by varunon9** [comment]
Is your netbeans using Java 8?

**Comment by varunon9** [comment]
Fixed.
