### ISSUE TITLE
Connection Ends 

### ISSUE THREAD

**Issue by hammadbutt** [varunon9/Remote-Control-PC#14]
The project works fine on BlueStacks Emulator but when running on a cellphone the connection ends with the following error messages at sever side when any remote feature is selected:

java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2601)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at remotecontrolpc.Server.connect(Server.java:73)
	at remotecontrolpc.MainScreenController$1$1.call(MainScreenController.java:168)
	at remotecontrolpc.MainScreenController$1$1.call(MainScreenController.java:164)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1409)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javafx.concurrent.Service.lambda$null$436(Service.java:718)
	at javafx.concurrent.Service$$Lambda$80/219993391.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.concurrent.Service.lambda$executeTask$437(Service.java:717)
	at javafx.concurrent.Service$$Lambda$78/1917189734.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by varunon9** [comment]
Android version/API? Error snapshots for Android (Android studio)? Did you try on some other device?

**Comment by hammadbutt** [comment]
Yes, I tried on Android 7.0 Nougat. 
I suppose it doesn't support Android versions above 6.0. It works fine till Android 6.0 as I checked back again on it.

**Comment by varunon9** [comment]
Try it again on Android 7. It's fixed now.
